version: '3.3'
services:
  geoipweb:
    image: razian/geoipweb
    container_name: geoipweb
    ports:
      - '3005:8080'
    volumes:
      - '/var/lib/GeoIP:/var/lib/GeoIP'
    environment:
      - GEOIPNAME=ipinfo.sh
    restart: unless-stopped
